### ISSUE TITLE
Error in "Specify receptor information"

### ISSUE THREAD

**Issue by yyxzju** [YuzheWangPKU/DiffPepBuilder#10]
File "/home/yyx/DiffPepBuilder/experiments/process_receptor.py", line 84, in read_peptide_info
raise ValueError(f"Receptor '{receptor_name}' not found in JSON file.")
ValueError: Receptor 'alk1' not found in JSON file.

I remember seeing this error in an issue before, and it was suggested to delete a certain cache folder, but today I found that the issue is no longer present

**Comment by YuzheWangPKU** [comment]
Please ensure that the JSON file specified by the `--peptide_info_path` flag includes the receptor entry `"alk1"`, as demonstrated in [this example file](https://github.com/YuzheWangPKU/DiffPepBuilder/blob/main/examples/receptor_data/de_novo_cases.json). Regarding the similar issue you mentioned, you can find more details in [this issue](https://github.com/YuzheWangPKU/DiffPepBuilder/issues/9). Please note that this problem has been addressed in the latest version of our code.

**Comment by yyxzju** [comment]
![image](https://github.com/user-attachments/assets/6a28e75b-ee9b-4e6d-9a0f-dc5aa6670ed7)
刚刚看源码找到问题了...原来判断是判断文件夹内的所有pdb是否在json里面

**Comment by YuzheWangPKU** [comment]
感谢指出！我们刚刚对代码进行了修改，现在受体在JSON中没有条目也可以正常处理了。

Yes, and apologies for the inconvenience! The script is designed to facilitate the batch processing of multiple receptors. We have just made slight modifications to the code to support scenarios where some receptors might be processed without their prior details being recorded in the JSON file.
