### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by pengzhangzhi** [YuzheWangPKU/DiffPepBuilder#5]
Hi, 
Great work and thanks for opening everything! I appreciate the availability of the training data. I notice the training code is also available but no instructions on how to set it up. I would love to reproduce the training code.

**Comment by YuzheWangPKU** [comment]
Thank you for your support of our work! We have now updated the training protocol in the README file and released the full datasets on [Zenodo](https://zenodo.org/records/13744959). Please review the changes and feel free to reach out if any issues arise.
