### ISSUE TITLE
RuntimeError: stack expects each tensor to be equal size, but got [36] at entry 0 and [37] at entry 1.

### ISSUE THREAD

**Issue by Charlesjc-lab** [YuzheWangPKU/DiffPepBuilder#7]
When I run the inference for a target protein generation, I get an error:
RuntimeError: stack expects each tensor to be equal size, but got [36] at entry 0 and [37] at entry 1.
Is there a solution?

**Comment by YuzheWangPKU** [comment]
Could you please provide additional information to help us reproduce the issue? Alternatively, if the problem occurs while running inference locally on your machine, please try using our [Colab Notebook](https://colab.research.google.com/github/YuzheWangPKU/DiffPepBuilder/blob/main/examples/DiffPepBuilder_demo.ipynb) to check if the issue persists.

**Comment by Charlesjc-lab** [comment]
The issue was successfully resolved by changing the command from 
“torchrun --nproc-per-node=3” to “torchrun --nproc-per-node=2” or “torchrun --nproc-per-node=4” .

**Comment by YuzheWangPKU** [comment]
We have identified that this error may arise during the batching process when `(samples_per_length % num_gpus) != 0`. We are actively working on a resolution for this issue. In the meantime, please ensure that `samples_per_length` and `num_gpus` are configured to meet this requirement. We apologize for the inconvenience this may cause.
