### ISSUE TITLE
Specify some amino acids of binder

### ISSUE THREAD

**Issue by xtzhang0216** [YuzheWangPKU/DiffPepBuilder#8]
hi, this is a wonderful work!
I'm wondering if I can fix part of the peptide. For example, I want the generated peptides to be SDRXXXXDDG, and I want the model to help me design the X residue. If not, do you have any suggestions for me to realize this requirement?
thanks in advance

**Comment by YuzheWangPKU** [comment]
Thank you for your support of our work and sorry for the late response! Currently, our model does not support peptide inpainting, but we are actively working on integrating this functionality into the upcoming version. To the best of our knowledge, there are no existing deep learning methods that specifically focus on this task. You might consider using ProteinMPNN if the native/reference protein-peptide complex structure is available. Alternatively, you could try manually modifying the `PepGenDataset` class in `experiments/run_inference.py` file in our model to set specific residues for the peptide. This approach could potentially guide the model to preserve the fixed parts of the sequence (_not tested previously_).
